In [1]:
import pandas
import numpy as np

In [2]:
# The following is a DataFrame showing monthly Net Operating Income (NOI) of some imagined real estate assets

# The DataFrame is organized with one row per property, and one column per month for each month in 2020 and 2021

# You can assume for this exercise that the data is complete, but the values may be positive or negative

df = pandas.read_csv('sample_df.csv')
df.index = df['Unnamed: 0'].values
df = df.drop(columns='Unnamed: 0')
df

,2020-01-01,2020-02-01,2020-03-01,2020-04-01,2020-05-01,2020-06-01,2020-07-01,2020-08-01,2020-09-01,2020-10-01,...,2021-03-01,2021-04-01,2021-05-01,2021-06-01,2021-07-01,2021-08-01,2021-09-01,2021-10-01,2021-11-01,2021-12-01
Property A,23083,35157,-4265,-4654,10976,16702,20167,22477,23543,45211,...,-594,27102,36633,2416,35090,44584,27241,-3840,37616,28752
Property B,-6723,6991,2584,-3622,-1583,25489,-4522,45589,5576,13409,...,35826,17299,39667,6891,36696,26685,1697,7146,12011,20351
Property C,42150,-1337,-6966,33105,25372,6412,9780,-1772,32078,37706,...,1469,28253,28914,11801,-3935,36747,8931,38141,26432,31200
Property D,46960,12672,8196,24763,35993,39596,37523,-6642,39804,29788,...,41726,-8898,-6415,26670,30062,2406,33835,16203,-637,28276
Property E,2478,21201,-5592,28917,5564,12989,38447,39453,38232,33739,...,34661,12573,6128,37439,48773,28294,-4795,2832,45731,3774
Property F,-9892,6097,39393,8647,31132,11195,23230,14340,29540,7448,...,24970,-1964,46108,-4063,25607,-342,46428,30569,23241,-7083
Property G,10020,7719,-5106,40026,-5090,17631,-5473,11028,17604,25964,...,-763,16497,-9928,-5227,43087,-7783,-4954,17604,33766,22877
Property H,46084,2810,32807,26024,-6699,18922,-660,28994,5178,36364,...,-3260,13189,13119,29770,42568,6473,24209,10757,48079,2938

In [3]:
# Calculate the total annual NOI for each property for both 2020 and 2021
# Solution should be a DataFrame with columns for YEAR, PROPERTY NAME, and AVERAGE NOI

In [4]:
# Calculate the average monthly NOI for each property for both 2020 and 2021 CONSIDERING ONLY POSITIVE MONTHS
# Solution should be a DataFrame with columns for YEAR, PROPERTY NAME, and AVERAGE NOI

In [5]:
# Create a monthly time-series chart showing the month-over-month change in average NOI for all properties

In [6]:
df_design = pandas.read_csv('design_matrix.csv').drop(columns='Unnamed: 0')

cols_x = [col for col in df_design.columns if 'noi' not in col]
col_y = 'noi_per_sqft'
df_design

,nooffloors,NATIONAL_RISK_INDEX,FLOODING_RISK_SCORE,POPULATION,MEDIAN_HHI,MEDIAN_HV,PCT_UNINSURED,UNEMPLOYMENT_RATE,transport_warehouse_employment_pct,closest_shipping,buildingage,nra,singletenant,IS_URBAN,IS_SUBURBAN,IS_RURAL,IS_LEED_CERTIFIED,IS_ESTAR_CERTIFIED,noi_per_sqft
0,1,39.173124,18.577293,5529213,83160,574094,0.084349,0.073232,0.134972,1.179929,12,317500,0,0,1,0,0,0,65.133588
1,1,39.318216,21.288636,5952054,117947,1371535,0.042402,0.052452,0.063493,1.292438,7,91541,0,0,1,0,0,0,126.776106
2,1,16.144807,16.049654,7506908,74202,284497,0.077295,0.072683,0.067969,2.578309,2,360391,0,0,1,0,1,0,33.399628
3,1,25.984613,13.245715,2444846,76701,464829,0.058947,0.049876,0.057501,11.282572,27,294912,0,1,0,0,0,0,44.066576
4,1,25.984613,13.245715,2445689,76699,464804,0.058944,0.049878,0.056754,6.886254,13,75200,0,1,0,0,1,0,46.761205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,38.434642,29.848958,3867266,91728,610416,0.055256,0.048705,0.046947,4.437721,15,72000,0,1,0,0,1,0,56.753488
96,1,29.221658,5.660086,2929269,87027,510668,0.056866,0.053316,0.077996,1.580224,19,517350,0,0,1,0,0,0,63.067867
97,1,29.221658,5.660086,2914931,86922,508815,0.056997,0.053272,0.077804,1.005822,21,474403,1,0,1,0,0,0,52.472948
98,1,26.691771,8.619711,3534145,127238,1565028,0.039057,0.049768,0.018083,5.177695,33,900870,1,0,1,0,0,0,154.867481
99,1,16.115608,7.312075,6226829,75407,283837,0.162895,0.054291,0.073935,9.558716,4,1400000,0,0,1,0,0,0,35.307718

In [ ]:
# Compare models with K-Fold CV using the DataFrame above

# You may use the modeling package of your choice (scikit-learn, pycaret, tensorflow, etc.)

# Choose two different regression models (e.g. Linear Regression and Gradient Boosting Regression) and compare the results of a
# K-Fold CV. 

from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import GradientBoostingRegressor

X = df_design[cols_x].values
y = df_design[col_y].values